/****************************************************
 * Description: This class generates and formats the 3D visualisation widget.
 * It embeds the plotted 3D visualisation generated by plotter into the widget.
 * It also triggers graph changes via connections (calls function when changed/clicked)
 *
 * Author/s: Monique Kuhn
****************************************************/

#include "datamodel.h"
#include "ui_datamodel.h"

/***************************************************/

DataModel::DataModel(QWidget *parent) :
    QDialog(parent),
    ui(new Ui::DataModel)
{
    ui->setupUi(this);
    generate3DWidget();
}

DataModel::~DataModel()
{
    delete ui;
}

/***************************************************/
/*Generates the 3D widget with all design components (buttons, container for plot, and additional prompts)*/
void DataModel::generate3DWidget(){
    Q3DScatter* graph = new Q3DScatter();
    /*The following segment of code sets up the widget's layout. In order:
        Size, Container (position and size), Window Title, Lists,
        Checkboxes, Buttons, combo boxes*/

    /*-------Size, Layout, Widget Title (Widget & Containers)-------*/
    QSize screenSize = graph->screen()->size();
    QWidget* container = QWidget::createWindowContainer(graph);
    container->setMinimumSize(QSize(screenSize.width() / 2, screenSize.height() / 1.3));
    container->setMaximumSize(screenSize);
    container->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding); //for dynamic scaling
    container->setFocusPolicy(Qt::StrongFocus);

    QHBoxLayout* hLayout = new QHBoxLayout(this);
    QVBoxLayout* vLayout = new QVBoxLayout();
    hLayout->addWidget(container, 1);
    hLayout->addLayout(vLayout);
    this->setWindowTitle(QStringLiteral("Drone Data Visualisation"));

    /*----------------------------Lists-----------------------------*/
    QComboBox* themeList = new QComboBox(this);
    themeList->addItem(QStringLiteral("Qt"));
    themeList->addItem(QStringLiteral("Primary Colors"));
    themeList->addItem(QStringLiteral("Digia"));
    themeList->addItem(QStringLiteral("Stone Moss"));
    themeList->addItem(QStringLiteral("Army Blue"));
    themeList->addItem(QStringLiteral("Retro"));
    themeList->addItem(QStringLiteral("Ebony"));
    themeList->addItem(QStringLiteral("Isabelle"));
    themeList->setCurrentIndex(6);

    QComboBox* itemStyleList = new QComboBox(this);
    itemStyleList->addItem(QStringLiteral("Sphere"), int(QAbstract3DSeries::MeshSphere));
    itemStyleList->addItem(QStringLiteral("Cube"), int(QAbstract3DSeries::MeshCube));
    itemStyleList->addItem(QStringLiteral("Minimal"), int(QAbstract3DSeries::MeshMinimal));
    itemStyleList->addItem(QStringLiteral("Point"), int(QAbstract3DSeries::MeshPoint));
    itemStyleList->setCurrentIndex(0);

    /*------------------------Check Boxes----------------------------*/
    QCheckBox* smoothCheckBox = new QCheckBox(this);
    smoothCheckBox->setText(QStringLiteral("Smooth dots"));
    smoothCheckBox->setChecked(true);

    QCheckBox* backgroundCheckBox = new QCheckBox(this);
    backgroundCheckBox->setText(QStringLiteral("Show background"));
    backgroundCheckBox->setChecked(true);

    QCheckBox* gridCheckBox = new QCheckBox(this);
    gridCheckBox->setText(QStringLiteral("Show grid"));
    gridCheckBox->setChecked(true);

    /*---------------------------Buttons-----------------------------*/
    QPushButton* labelButton = new QPushButton(this);
    labelButton->setText(QStringLiteral("Change label style"));

    QPushButton* cameraButton = new QPushButton(this);
    cameraButton->setText(QStringLiteral("Change camera preset"));

    QComboBox* shadowQuality = new QComboBox(this);
    shadowQuality->addItem(QStringLiteral("None"));
    shadowQuality->addItem(QStringLiteral("Low"));
    shadowQuality->addItem(QStringLiteral("Medium"));
    shadowQuality->addItem(QStringLiteral("High"));
    shadowQuality->addItem(QStringLiteral("Low Soft"));
    shadowQuality->addItem(QStringLiteral("Medium Soft"));
    shadowQuality->addItem(QStringLiteral("High Soft"));
    shadowQuality->setCurrentIndex(4);

    /*------------------------Combo boxes-----------------------------*/
    QFontComboBox* fontList = new QFontComboBox(this);
    fontList->setCurrentFont(QFont("Arial"));

    /*------------Add all components to the layout--------------------*/
    vLayout->addWidget(labelButton, 0, Qt::AlignTop);
    vLayout->addWidget(cameraButton, 0, Qt::AlignTop);
    vLayout->addWidget(backgroundCheckBox);
    vLayout->addWidget(gridCheckBox);
    vLayout->addWidget(smoothCheckBox, 0, Qt::AlignTop);
    vLayout->addWidget(new QLabel(QStringLiteral("Change dot style")));
    vLayout->addWidget(itemStyleList);
    vLayout->addWidget(new QLabel(QStringLiteral("Change theme")));
    vLayout->addWidget(themeList);
    vLayout->addWidget(new QLabel(QStringLiteral("Adjust shadow quality")));
    vLayout->addWidget(shadowQuality);
    vLayout->addWidget(new QLabel(QStringLiteral("Change font")));
    vLayout->addWidget(fontList, 1, Qt::AlignTop);

    vLayout->addWidget(new QLabel(QStringLiteral("Shortcuts:")));
    vLayout->addWidget(new QLabel(QStringLiteral("Zoom: +/- or scroll with mouse wheel")));
    vLayout->addWidget(new QLabel(QStringLiteral("Rotate: Mouse right click + drag")));

    modifier = new  Plotter(graph);

    /*The following segment of code sets up the widget's layout. In order:
        Size, Container (position and size), Window Title, Lists,
        Checkboxes, Buttons, combo boxes*/

    QObject::connect(cameraButton, &QPushButton::clicked, modifier,
        & Plotter::changePresetCamera);
    QObject::connect(labelButton, &QPushButton::clicked, modifier,
        & Plotter::changeLabelStyle);
    QObject::connect(backgroundCheckBox, &QCheckBox::stateChanged, modifier,
        & Plotter::setBackgroundEnabled);
    QObject::connect(gridCheckBox, &QCheckBox::stateChanged, modifier,
        & Plotter::setGridEnabled);
    QObject::connect(smoothCheckBox, &QCheckBox::stateChanged, modifier,
        & Plotter::setSmoothDots);

    QObject::connect(modifier, & Plotter::backgroundEnabledChanged,
        backgroundCheckBox, &QCheckBox::setChecked);
    QObject::connect(modifier, & Plotter::gridEnabledChanged,
        gridCheckBox, &QCheckBox::setChecked);
    QObject::connect(itemStyleList, SIGNAL(currentIndexChanged(int)), modifier,
        SLOT(changeStyle(int)));

    QObject::connect(themeList, SIGNAL(currentIndexChanged(int)), modifier,
        SLOT(changeTheme(int)));

    QObject::connect(shadowQuality, SIGNAL(currentIndexChanged(int)), modifier,
        SLOT(changeShadowQuality(int)));

    QObject::connect(modifier, & Plotter::shadowQualityChanged, shadowQuality,
        &QComboBox::setCurrentIndex);
    QObject::connect(graph, &Q3DScatter::shadowQualityChanged, modifier,
        & Plotter::shadowQualityUpdatedByVisual);

    QObject::connect(fontList, &QFontComboBox::currentFontChanged, modifier,
        & Plotter::changeFont);

    QObject::connect(modifier, & Plotter::fontChanged, fontList,
        &QFontComboBox::setCurrentFont);
}

/*Don't delete this! Integral to scatter plot being generated- no one knows why D:*/
void DataModel::showEvent( QShowEvent* _event ) {
    QWidget::showEvent(_event);
    modifier->toggleItemCount();
}



